# -*- coding: utf-8 -*-
"""Day_9_Morning_Models_in_Langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHdcTACixFYWWrUqaFbU738zAYEKrQXA

##**Welcome to Langchain**
"""

print("Welcome to Gen-AI on google colab")

# Models API From Langchain
    # Provides common functions to interact with
        # Embedding
        # LLMs
        # Chat Model
    # Unified Layer - Models from various families (OpenAI, Ollama, etc) can be used with the same interface

# Common / Unified Functions for LLMs and Chat Models from various families

    # 1 invoke() - > to send a prompt to the model and get the response

# Note - Extensively use the invoke() method.

# Models API in Langchain - helps developers to simplify
# application developement - chatbots, QnA, RAG, Agents

!pip install -q ollama

# Define your prompt
prompt = "What is the capital of France?"

# Example 1 - Ollama cloud model

# First, ensure the ollama library is installed in your Colab environment

from google.colab import userdata
from ollama import Client

# Fetch the API key securely from Colab Secrets
ollama_api_key = userdata.get('OLLAMA_API_KEY')

# Initialize the Ollama Cloud Client
client = Client(
    host="https://ollama.com",
    headers={
        "Authorization": f"Bearer {ollama_api_key}"
    }
)

# Execute the chat completion call
response = client.chat(
    model="gpt-oss:20b-cloud",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

print("The response from Ollama cloud model is:\n")
#print(response)

# Uncomment the line below if you only want to extract the clean message body text
print(response["message"]["content"])

# Example 2 - OpenAI Cloud

from google.colab import userdata

# Fetch the API key securely from Colab Secrets
openai_api_key = userdata.get('OPENAI_API_KEY')

from openai import OpenAI

# Explicitly pass the api_key parameter to the client
client = OpenAI(api_key=openai_api_key)

response = client.responses.create(
    model="gpt-5.4-nano",
    input=prompt,
)
print("The response from OpenAI cloud model is : \n")
print(response.output_text)

#from langchain_ollama import ChatOllama
#from langchain_ollama import ChatOpenAI

# Example 3 - Using Langchain - Models - invoke()

!pip install -q langchain-ollama

from google.colab import userdata
from langchain_ollama import ChatOllama

# 1. Fetch the API key securely from Colab Secrets
ollama_api_key = userdata.get('OLLAMA_API_KEY')

# 2. Initialize the LangChain ChatOllama model with cloud configs
model = ChatOllama(
    model="gpt-oss:20b-cloud",
    base_url="https://ollama.com",  # Directly targets Ollama Cloud instead of localhost
    client_kwargs={
        "headers": {
            "Authorization": f"Bearer {ollama_api_key}"
        }
    }
)

# 3. Define your prompt
# prompt = "What is the capital of France?"

# 4. Execute the call using the LangChain invoke method
response = model.invoke(prompt)

print("\nExtracted clean text content:\n")
# To get just the text body, extract the content attribute
print(response.content)

# Upgrade langchain-core and langchain-openai to resolve dependency conflicts
!pip install -U -q langchain-core langchain-openai

# Completely remove conflicting fragments
!pip uninstall -y langchain langchain-core langchain-openai

# Reinstall clean, tightly matched latest versions
!pip install -qU langchain-core langchain-openai

from google.colab import userdata
from langchain_openai import ChatOpenAI

# Fetch the key securely
openai_api_key = userdata.get('OPENAI_API_KEY')

# Initialize and invoke safely
model = ChatOpenAI(
    model="gpt-5.4-nano",
    #model="gpt-5.6",
    api_key=openai_api_key
)

prompt = "What is the capital of France?"
response = model.invoke(prompt)
print(response.content)

# Example 4 - Introduce Tiktoken library to calculate input and output tokens

!pip install Tiktoken

from google.colab import userdata
from langchain_openai import ChatOpenAI
import tiktoken

# 1. Fetch the key securely
openai_api_key = userdata.get('OPENAI_API_KEY')

# 2. Set up the local token encoder
# Using 'cl100k_base' as a reliable proxy for modern token counting
encoder = tiktoken.get_encoding("cl100k_base")

# 3. Define prompt and calculate local input tokens
prompt = "What is the capital of France"
input_tokens = len(encoder.encode(prompt))
print(f"--- Local Token Analysis Before Request ---")
print(f"Input Prompt: '{prompt}'")
print(f"Local Input Token Count: {input_tokens}\n")

# 4. Initialize and invoke model
model = ChatOpenAI(
    model="gpt-5.4-nano",
    api_key=openai_api_key
)

print("Sending request to OpenAI...")
response = model.invoke(prompt)

# 5. Extract output and calculate local output tokens
output_text = response.content
output_tokens = len(encoder.encode(output_text))

print(f"\n--- Model Response ---")
print(output_text)

print(f"\n--- Local Token Analysis After Request ---")
print(f"Local Output Token Count: {output_tokens}")
print(f"Total Local Session Tokens: {input_tokens + output_tokens}")

# Example 5 - Above chat bot code - dynamic user input for prompt

from google.colab import userdata
from langchain_openai import ChatOpenAI
import tiktoken

# 1. Fetch the key securely
openai_api_key = userdata.get('OPENAI_API_KEY')

# 2. Set up the local token encoder
# Using 'cl100k_base' as a reliable proxy for modern token counting
encoder = tiktoken.get_encoding("cl100k_base")

# 3. Define prompt and calculate local input tokens

prompt = input("Enter your prompt: \n")

input_tokens = len(encoder.encode(prompt))
print(f"--- Local Token Analysis Before Request ---")
print(f"Input Prompt: '{prompt}'")
print(f"Local Input Token Count: {input_tokens}\n")


# 4. Initialize and invoke model
model = ChatOpenAI(
    model="gpt-5.4-nano",
    api_key=openai_api_key
)

print("Sending request to OpenAI...")
response = model.invoke(prompt)

# 5. Extract output and calculate local output tokens
output_text = response.content
output_tokens = len(encoder.encode(output_text))

print(f"\n--- Model Response ---")
print(output_text)

print(f"\n--- Local Token Analysis After Request ---")
print(f"Local Output Token Count: {output_tokens}")
print(f"Total Local Session Tokens: {input_tokens + output_tokens}")

# Example 6 - Interact with Ollama & OpenAI Cloud models

from google.colab import userdata
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
import tiktoken

# 1. Fetch the key securely
openai_api_key = userdata.get('OPENAI_API_KEY')
ollama_api_key = userdata.get('OLLAMA_API_KEY')

# 2. Set up the local token encoder
# Using 'cl100k_base' as a reliable proxy for modern token counting
encoder = tiktoken.get_encoding("cl100k_base")

# 3. Define prompt and calculate local input tokens

prompt = input("Enter your prompt: \n")

input_tokens = len(encoder.encode(prompt))
print(f"--- Local Token Analysis Before Request ---")
print(f"Input Prompt: '{prompt}'")
print(f"Local Input Token Count: {input_tokens}\n")


# 4. Initialize and invoke model - Ollama

model1 = ChatOllama(
    model="gpt-oss:20b-cloud",
    base_url="https://ollama.com",  # Directly targets Ollama Cloud instead of localhost
    client_kwargs={
        "headers": {
            "Authorization": f"Bearer {ollama_api_key}"
        }
    }
)

response_ollama = model1.invoke(prompt)

print("Sending request to Ollama...")
response_ollama = model.invoke(prompt)

# 5. Extract output and calculate local output tokens
output_text = response_ollama.content
output_tokens = len(encoder.encode(output_text))

print(f"\n--- Model Response ---")
print(output_text)

print(f"\n--- Local Token Analysis After Request ---")
print(f"Local Output Token Count: {output_tokens}")
print(f"Total Local Session Tokens: {input_tokens + output_tokens}")

# 4. Initialize and invoke model - OpenAI
model = ChatOpenAI(
    model="gpt-5.4-nano",
    api_key=openai_api_key
)

print("Sending request to OpenAI...")
response = model.invoke(prompt)

# 5. Extract output and calculate local output tokens
output_text = response.content
output_tokens = len(encoder.encode(output_text))

print(f"\n--- Model Response ---")
print(output_text)

print(f"\n--- Local Token Analysis After Request ---")
print(f"Local Output Token Count: {output_tokens}")
print(f"Total Local Session Tokens: {input_tokens + output_tokens}")

# End of the Notebook

