# -*- coding: utf-8 -*-
"""Day_16_Morning_RAG_Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZu0D6JKZykLhcUA4wxU5VD5tAbVAR2k

# **Welcome to Day-16 / Session-16 => RAG Implementation**
"""

!pip install -q wikipedia langchain langchain-community langchain-openai langchain-classic langchain_chroma chromadb pypdf unstructured[pdf,csv,docx,excel] beautifulsoup4 html2text gradio

import os
import gradio as gr

from langchain_community.document_loaders import PyPDFLoader, CSVLoader, TextLoader, WebBaseLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_openai import ChatOpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate
from google.colab import userdata
import shutil
import traceback # Import traceback for detailed error logging
import datetime # NEW: For unique directory names
import uuid # NEW: For unique directory names

import requests # New import for robust URL loading
from bs4 import BeautifulSoup # New import for robust URL loading
import html2text # New import for robust URL loading
from langchain_core.documents import Document # Ensure Document is imported for robust URL loading

# --- Configuration and Setup ---

# Set OpenAI API key from Colab secrets
try:
    os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
    if not os.environ["OPENAI_API_KEY"]:
        raise ValueError("OPENAI_API_KEY secret is empty.")
except userdata.SecretNotFoundError:
    print("OPENAI_API_KEY not found in Colab secrets. Please add it to the Secrets panel.")
    exit()
except Exception as e:
    print(f"Error accessing Colab secrets: {e}")
    exit()

# Agenda - RAG

  # Embeddings
  # Vectors, Vector Stores and Vector Databases
  # FAISS / ChromaDB
  # Similarity Search -> Retrieve doc containing the required text - matching with input

  # Augmented Response Generation
        # Document Loaders - pdf, web,csv,text
        # Text Splitters
        # llm/chat-models -> RAG
                            # Chat-bot / QnA -> Interact / chat with the external data/knowledge - documents - website/s, csv, text, pdf

# External Data -> List of Sentences ref to as Documents
# 1 Embedding - Text to Emeddings
# 2 Vector Database -> Chromadb
# 3 Integrated a chat-model

from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_chroma import Chroma
from langchain_classic.chains import RetrievalQA
from langchain_core.prompts import PromptTemplate
import openai
from google.colab import userdata
from langchain_openai import ChatOpenAI
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

model_name = 'gpt-5.4-nano'
model = ChatOpenAI(model_name=model_name, openai_api_key=OPENAI_API_KEY)

# 1. Define Models
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

llm = ChatOpenAI(model_name=model_name, openai_api_key=OPENAI_API_KEY)

# 2. External Knowledge
documents = [
    "Zensar Technologies - is a leading Digital Transformation and AI company.",
    "AI is rapidly changing the technology world.",
    "Artificial Intelligience is rapidly growing.",
    "Zensar is in Pune",
    "Pune is a city of education.",
    "New Delhi is the capital of India.",
    "The capital of France is Paris",
    "I am Sandip",
    "I work with Zensar as a Technology Trainer for Data & AI",
    "I am from Pune"
]

# 3. Create Vector Store
vector_store = Chroma.from_texts(texts=documents, embedding=embeddings)

# 4. Define a Custom Prompt Template (The "Strict" Guardrail)
template = """Use the following pieces of context/external knowledge to answer the question at the end.
If you don't know the answer based strictly on the context/external knowledge provided, just say "I don't know",
do not try to make up an answer or use your pretrained knowledge.

Context: {context}

Question: {question}

Helpful Answer:"""

RA_PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"]
)

# 5. Set up Retrieval Chain with the strict prompt
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vector_store.as_retriever(search_kwargs={"k": 2}),
    chain_type_kwargs={"prompt": RA_PROMPT} # This injects your strict rules
)

# 6. Execute
prompt = input("Enter your prompt: \n")
response = qa_chain.invoke(prompt)

print("\nLLM Response:")
print(response["result"])

# Non-Strict -> uses external & own knowledge

from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_chroma import Chroma
from langchain_classic.chains import RetrievalQA
from langchain_core.prompts import PromptTemplate
import openai
from google.colab import userdata
from langchain_openai import ChatOpenAI
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

model_name = 'gpt-5.4-nano'
model = ChatOpenAI(model_name=model_name, openai_api_key=OPENAI_API_KEY)

# 1. Define Models
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

llm = ChatOpenAI(model_name=model_name, openai_api_key=OPENAI_API_KEY)

# 2. External Knowledge
documents = [
    "Zensar Technologies - is a leading Digital Transformation and AI company.",
    "AI is rapidly changing the technology world.",
    "Artificial Intelligience is rapidly growing.",
    "Zensar is in Pune",
    "Pune is a city of education.",
    "New Delhi is the capital of India.",
    "The capital of France is Paris",
    "I am Sandip",
    "I work with Zensar as a Technology Trainer for Data & AI",
    "I am from Pune"
]

# 3. Create Vector Store
vector_store = Chroma.from_texts(texts=documents, embedding=embeddings)

# 4. Define a Custom Prompt Template (The "Strict" Guardrail)
template = """Use the following pieces of context/external knowledge to answer the question at the end.
If you don't know the answer based strictly on the context/external knowledge provided, use your own pretrained knowledge to answer the questions.

Context: {context}

Question: {question}

Helpful Answer:"""

RA_PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"]
)

# 5. Set up Retrieval Chain with the strict prompt
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vector_store.as_retriever(search_kwargs={"k": 2}),
    chain_type_kwargs={"prompt": RA_PROMPT} # This injects your strict rules
)

# 6. Execute
prompt = input("Enter your prompt: \n")
response = qa_chain.invoke(prompt)

print("\nLLM Response:")
print(response["result"])

# RAG - Retrival Augmented Generation

    # Document Loaders - Ingest data from various resources - web-pages, pdf, csv, github...
    # Text Splitters - Smaller & Manageable chunks
    # Embeddings
    # Vector Stores / DBs
    # Retrive - Chat-Models / LLMs & Generate Responses to the user questions/promts.

# Document Loaders
# 1 Web-base loader

# Example 1 - Web-base loader

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Step 1 - Document Loaders

url = ["https://www.geeksforgeeks.org/python/python-lists/"]

loader = WebBaseLoader(url)
#print(type(loader))

docs = loader.load()

#print(type(docs))

#print(docs[0].page_content)

# Text Splitters
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, # Max charaters per chunk
    chunk_overlap=100 # Shared characters between the chunks
)

chunks = text_splitter.split_documents(docs)
print("The data type of splitted chunks of text is: ", type(chunks))
print("The total chunks of the text are: ",len(chunks))
print("The contents retrieved below are from: ", chunks[1].metadata['source'])

print(chunks[1].page_content)

# Multiple URLs

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Step 1 - Document Loaders

url = ["https://www.geeksforgeeks.org/python/python-lists/",
       "https://www.geeksforgeeks.org/python/python-tuples/",
       "https://www.geeksforgeeks.org/python/python-functions/",
       "https://www.tutorialspoint.com/python/python_variables.htm",
       "https://www.tutorialspoint.com/python/python_if_else.htm"
       ]


loader = WebBaseLoader(url)
#print(type(loader))

docs = loader.load()

#print(type(docs))

#print(docs[0].page_content)

# Text Splitters
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, # Max charaters per chunk
    chunk_overlap=100 # Shared characters between the chunks
)

chunks = text_splitter.split_documents(docs)
print("The data type of splitted chunks of text is: ", type(chunks))
print("The total chunks of the text are: ",len(chunks))
print("The contents retrieved below are from: ", chunks[45].metadata['source'])

print(chunks[45].page_content)

# Example 2 - Document Loaders & Text Splitters

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# url_1 = "https://www.geeksforgeeks.org/python/python-lists/"

# Step 1 - Document Loaders

url = ["https://www.geeksforgeeks.org/python/python-lists/",
       "https://www.geeksforgeeks.org/python/python-tuples/",
       "https://www.geeksforgeeks.org/python/python-functions/",
       "https://www.geeksforgeeks.org/python/python-operators/",
       "https://www.geeksforgeeks.org/python/conditional-statements-in-python/",
       "https://www.geeksforgeeks.org/python/loops-in-python/",
       "https://www.tutorialspoint.com/python/python_variables.htm",
       "https://www.tutorialspoint.com/python/python_if_else.htm"]

loader = WebBaseLoader(url)

docs = loader.load()

# Text Splitters
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, # Max charaters per chunk
    chunk_overlap=100 # Shared characters between the chunks
)

chunks = text_splitter.split_documents(docs)
print("The total chunks of the text are: ",len(chunks))

# Example 3 - Document Loaders, Text Splitters , Embeddings & Vector Databases

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# url_1 = "https://www.geeksforgeeks.org/python/python-lists/"

# Step 1 - Document Loaders

url = ["https://www.geeksforgeeks.org/python/python-lists/",
       "https://www.geeksforgeeks.org/python/python-tuples/",
       "https://www.geeksforgeeks.org/python/python-functions/",
       "https://www.geeksforgeeks.org/python/python-operators/",
       "https://www.geeksforgeeks.org/python/conditional-statements-in-python/",
       "https://www.geeksforgeeks.org/python/loops-in-python/",
       "https://www.tutorialspoint.com/python/python_variables.htm",
       "https://www.tutorialspoint.com/python/python_if_else.htm"]

loader = WebBaseLoader(url)

docs = loader.load()

# Step 2 - Text Splitters
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, # Max charaters per chunk
    chunk_overlap=100 # Shared characters between the chunks
)

chunks = text_splitter.split_documents(docs)
print("The total chunks of the text are: ",len(chunks))

# Step-3 - Embeddings (Convert the chunks of Text into Embeddings)

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

# Step-4 Save/Write the embeddings chunks into chroma db - persistant in Memory and/or write on disk.
vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="./chroma_db",
    collection_name="python_docs_db"
    )
print("The vector database initialized successfully")

# Let's start querying the vector database (Similarity Search)

query = "what are the various types of variables in Python"

result = vector_db.similarity_search(query, k=1)
print("\n The top search results for the given query are below: \n")

print(result[0].page_content)
print(result[0].metadata['source'])

# Example 4 - Integrate Chat-Model - RAG - Augmented Resonses only from given context/external knowledge/data/documents.

# 4. Define a Custom Prompt Template (The "Strict" Guardrail)
template = """Use the following pieces of context to answer the question at the end.
If you don't know the answer based strictly on the context provided, just say "I don't know",
do not try to make up an answer or use your own / pretrained knowledge.

Context: {context}

Question: {question}

Python QnA Chat-Bot Answer:"""

QA_CHAIN_PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"]
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vector_db.as_retriever(search_kwargs={"k": 1}),
    return_source_documents=True, # Add this line to return source documents
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT} # This injects your strict rules
)

query="What are the various ways to create lists in Python"

result = qa_chain.invoke({"query":query})
print(f"Answer to given {query} is : \n", result["result"])

# Access source documents safely
if "source_documents" in result and result["source_documents"]:
    print("The source of the answer is \n", result["source_documents"][0].metadata['source'])
else:
    print("No source documents found.")

# Step-5 - Query with out of context question

query1 ="What is the capital of India"

result1 = qa_chain.invoke({"query":query1})
print(f"Answer to given {query1} is : \n", result1["result"])

# Access source documents safely
if "source_documents" in result1 and result1["source_documents"]:
    print("The source of the answer is \n", result1["source_documents"][0].metadata['source'])
else:
    print("No source documents found.")

# Example 5 - Above Example as a dynamic python QnA Chat-bot

# 4. Define a Custom Prompt Template (The "Strict" Guardrail)
template = """Use the following pieces of context to answer the question at the end.
If you don't know the answer based strictly on the context provided, just say "I don't know",
do not try to make up an answer or use external knowledge.

Context: {context}

Question: {question}

Python QnA Chat-Bot Answer:"""

QA_CHAIN_PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"]
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vector_db.as_retriever(search_kwargs={"k": 1}),
    return_source_documents=True, # Add this line to return source documents
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT} # This injects your strict rules
)

query= input("Enter your query here: \n")

result = qa_chain.invoke({"query":query})
print(f"Answer to given {query} is : \n", result["result"])

# Access source documents safely
if "source_documents" in result and result["source_documents"]:
    print("The source of the answer is \n", result["source_documents"][0].metadata['source'])
else:
    print("No source documents found.")

# 4. Define a Custom Prompt Template (The "Strict" Guardrail)
template = """Use the following pieces of context to answer the question at the end.
If you don't know the answer based strictly on the context provided, just say "I don't know",
do not try to make up an answer or use external knowledge.

Context: {context}

Question: {question}

Python QnA Chat-Bot Answer:"""

QA_CHAIN_PROMPT = PromptTemplate(
    template=template, input_variables=["context", "question"]
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vector_db.as_retriever(search_kwargs={"k": 1}),
    return_source_documents=True, # Add this line to return source documents
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT} # This injects your strict rules
)

while True:
  query= input("Enter your query here: \n")

  if query.lower() == "exit":
    print("Exiting the chat-bot")
    break

  result = qa_chain.invoke({"query":query})

  print(f"Answer to given {query} is : \n", result["result"])

  # Access source documents safely
  if "source_documents" in result and result["source_documents"]:
      # Only access the first document since k=1
      print("The source of the answer is \n", result["source_documents"][0].metadata['source'])
  else:
      print("No source documents found.")



# Example 6 - Dynamic RAG - Python QnA Chat-bot with UI.

import gradio as gr

# The qa_chain, llm, vector_db, and QA_CHAIN_PROMPT are already defined in previous cells.
# We will reuse them here.

def rag_chatbot_interface(query):
    if not query:
        return "Please enter a question.", ""

    result = qa_chain.invoke({"query": query})
    answer = result["result"]
    source = "No source documents found."

    if "source_documents" in result and result["source_documents"]:
        # Access the first document's source as k is set to 1
        source = result["source_documents"][0].metadata['source']

    return answer, source

# Create the Gradio interface
iface = gr.Interface(
    fn=rag_chatbot_interface,
    inputs=gr.Textbox(lines=2, placeholder="Enter your Python-related query here..."),
    outputs=[
        gr.Textbox(label="Answer"),
        gr.Textbox(label="Source Document URL", interactive=False)
    ],
    title="Python RAG QnA Chat-Bot",
    description="Ask questions about Python concepts like lists, tuples, functions, operators, conditional statements, and loops. The answers are generated strictly from the provided documentation."
)

# Launch the interface
iface.launch(debug=True)

# Example 6 - RAG - application with PDF Loader and Web-based loader

# 1. Install necessary libraries
# !pip install -q gradio pypdf langchain-community beautifulsoup4 --quiet

import os
import gradio as gr
from google.colab import userdata
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader, WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_classic.chains import RetrievalQA
from langchain_core.prompts import PromptTemplate

# Setup API Key
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

# Global variables
qa_chain = None

def process_data(file_output, web_url):
    global qa_chain

    # 2. Decide which loader to use based on input
    if file_output is not None:
        loader = PyPDFLoader(file_output.name)
        source_type = "PDF"
    elif web_url and web_url.strip():
        loader = WebBaseLoader(web_url)
        source_type = "URL"
    else:
        return "Error: Please upload a PDF OR enter a Website URL."

    try:
        docs = loader.load()

        # 3. Split the documents
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
        chunks = text_splitter.split_documents(docs)

        # 4. Create Vector Store
        embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
        vector_db = Chroma.from_documents(
            documents=chunks,
            embedding=embeddings
        )

        # 5. Setup LLM and Chain
        template = """Use the following pieces of context to answer the question at the end.
        If you don't know the answer or the information is not in the context, just say "I don't know",
        do not try to make up an answer. Keep the answer concise.

        {context}

        Question: {question}
        Helpful Answer:"""

        QA_CHAIN_PROMPT = PromptTemplate(input_variables=["context", "question"], template=template)
        llm = ChatOpenAI(model_name="gpt-5.4-nano", temperature=0)

        qa_chain = RetrievalQA.from_chain_type(
            llm,
            retriever=vector_db.as_retriever(search_kwargs={"k": 1}),
            return_source_documents=True,
            chain_type_kwargs={"prompt": QA_CHAIN_PROMPT}
        )

        return f"{source_type} Processed Successfully! You can now ask questions."
    except Exception as e:
        return f"Error: {str(e)}"

def chat_interface(user_query):
    global qa_chain
    if qa_chain is None:
        return "Error: Please process a data source before asking questions."

    result = qa_chain.invoke({"query": user_query})
    response = f"Answer: {result['result']}"

    if result['source_documents']:
        meta = result['source_documents'][0].metadata
        source = meta.get('source', 'Unknown')
        page = meta.get('page', 'N/A')
        response += f"\n\n(Source: {source}, Page/Info: {page})"

    return response

# 6. Build Gradio UI with Dual Loading Options
with gr.Blocks() as demo:
    gr.Markdown("# Multi-Loader RAG (PDF & Web) with GPT-5-Nano")

    with gr.Row():
        with gr.Column(scale=1):
            with gr.Tabs():
                with gr.TabItem("PDF Upload"):
                    file_input = gr.File(label="Upload PDF", file_types=[".pdf"])
                with gr.TabItem("Web URL"):
                    url_input = gr.Textbox(label="Enter Website URL", placeholder="https://example.com")

            process_btn = gr.Button("Process Data Source", variant="primary")
            status_msg = gr.Textbox(label="Status", interactive=False)

        with gr.Column(scale=2):
            query_input = gr.Textbox(label="Enter your query")
            answer_output = gr.Textbox(label="Response", interactive=False, lines=12)
            submit_btn = gr.Button("Ask Question")

    # Link functionality
    process_btn.click(
        fn=process_data,
        inputs=[file_input, url_input],
        outputs=status_msg
    )
    submit_btn.click(
        fn=chat_interface,
        inputs=query_input,
        outputs=answer_output
    )

demo.launch(debug=True)

# End of the Notebook

